// DDL data
window.DDL_DATA_MIN = {
      projects: [
        { id: "kyma", name: "kyma", nameLine2: "", cover: "#3B5F6A",
          service: "브랜드 운영 · 브랜드 SNS 운영",
          diagnosis: "시즌 기획과 운영이 분절되어 있어 브랜드 자산이 누적되지 않던 상태였습니다.",
          solution: "시즌 — 제품 — 채널을 하나의 운영 시트로 통합하고 주간 리듬을 설계했습니다.",
          identity: "'파도의 결' — Waves, Quieted.",
          scope: ["Brand Operation", "Brand SNS"],
          before: "24FW", after: "25SS",
        },
        { id: "ruhel", name: "ruhel", nameLine2: "", cover: "#2F3A3A",
          service: "브랜드 SNS 운영",
          diagnosis: "꾸준한 제품력에 비해 디지털 채널 노출이 약해 성장 속도가 제한적이었습니다.",
          solution: "SNS 콘텐츠 포맷을 영상 중심으로 전환하고 인플루언서 협업을 분기별로 운영했습니다.",
          identity: "'고요한 강도' — Quiet Intensity.",
          scope: ["Brand SNS", "Content"],
          before: "24FW", after: "25SS",
        },
        { id: "vivicate", name: "vivi", nameLine2: "cate", cover: "#D4838A",
          service: "브랜드 SNS 운영",
          diagnosis: "신규 런칭 후 브랜드 인지도 확보가 필요한 초기 단계 브랜드.",
          solution: "런칭 캠페인과 SNS 계정 성장 플랜을 설계하고 6개월간 밀착 운영했습니다.",
          identity: "'활기를 입다' — Wear the Spark.",
          scope: ["Brand SNS", "Campaign"],
          before: "—", after: "25 LAUNCH",
        },
        { id: "sunniesstudos", name: "sunnies", nameLine2: "studos", cover: "#C9A96E",
          service: "브랜드 SNS 운영",
          diagnosis: "컬러와 무드는 명확했으나 채널별 톤앤매너가 일관되지 않았습니다.",
          solution: "인스타·스레드 운영 가이드를 재정의하고 월간 캠페인 프레임을 도입했습니다.",
          identity: "'햇살의 문법' — Grammar of Sunlight.",
          scope: ["Brand SNS", "Content"],
          before: "24SS", after: "25SS",
        },
        { id: "aube-seoul", name: "aube", nameLine2: "seoul", cover: "#8A8574",
          service: "브랜드 운영 · 브랜드 SNS 운영",
          diagnosis: "오버사이즈 아우터 아이템만으로는 시장 내 포지셔닝의 모호함, 시즌 기획의 일관성 또한 부족한 상태였습니다. 25SS 시즌 운영 데이터에서 고객당 구매 수, 리턴 빈도 등의 지표가 브랜드 충성도 저하로 직접 확인되었습니다.",
          solution: "시장 포지션과 소비층의 니즈를 반영하여, 자체 개발한 '5단계 리브랜딩 캔버스' 프로세스를 적용했습니다. 브랜드의 본질을 재정의하고 전략적인 제품 개선을 단행했습니다.",
          identity: "'한국(동양)의 우아함을 입다'(Oriental Elegance)라는 명확하고 날카로운 브랜드 코어를 확보했습니다. 이를 통해 시장 내 독보적인 정체성 확립과 지속 가능한 성장 기반을 구축했습니다.",
          scope: ["Re-Branding", "Brand Consulting"],
          before: "25SS", after: "26SS",
        },
        { id: "dancing-grandma", name: "dancing", nameLine2: "grandma", cover: "#D99C4A",
          service: "브랜드 운영",
          diagnosis: "개성 강한 브랜드 톤에 비해 운영 체계가 따라가지 못하던 상태.",
          solution: "시즌 기획 — 생산 — 채널 운영 전 과정을 표준화하고 팀 내 R&R을 정비했습니다.",
          identity: "'춤추는 일상' — Joyful, Always.",
          scope: ["Brand Operation"],
          before: "24FW", after: "25SS",
        },
        { id: "thatmustnotbenamed", name: "thatmust", nameLine2: "notbenamed", cover: "#1E1E2A",
          service: "리브랜딩 · 브랜드 컨설팅",
          diagnosis: "강한 팬덤에 비해 브랜드 언어가 내부 코드에 머물러 있어 확장이 어려웠습니다.",
          solution: "코어 팬덤의 언어를 공공의 언어로 번역하는 커뮤니케이션 체계를 설계했습니다.",
          identity: "'이름 없는 것들의 이름' — The Unnamed, Named.",
          scope: ["Re-Branding", "Consulting"],
          before: "24FW", after: "25FW",
        },
        { id: "drrip", name: "drrip", nameLine2: "", cover: "#5A6B5F",
          service: "브랜드 SNS 운영",
          diagnosis: "제품 드랍 주기에 비해 콘텐츠 사이클이 짧아 노출이 분산되는 구조였습니다.",
          solution: "드랍 단위의 콘텐츠 캠페인을 설계하고 월간 리포트로 성과를 추적했습니다.",
          identity: "'한 방울의 무게' — Weight of a Drip.",
          scope: ["Brand SNS", "Campaign"],
          before: "24SS", after: "25SS",
        },
        { id: "musinsa", name: "musinsa", nameLine2: "", cover: "#141414",
          service: "브랜드 컨설팅",
          diagnosis: "입점 브랜드로서의 정체성과 자사몰 정체성 사이의 간극이 컸습니다.",
          solution: "채널별 포지셔닝을 분리하고, 시즌별 컨설팅 리듬을 도입했습니다.",
          identity: "'플랫폼과 브랜드 사이' — Between Platform & Brand.",
          scope: ["Brand Consulting"],
          before: "24FW", after: "25SS",
        },
      ],
      services: [
        { num: "01", ko: "브랜드 운영", en: "Brand Operation",
          body: "시즌 기획부터 생산, 자사몰·입점몰·오프라인 채널 운영까지. 브랜드의 매 시즌을 실무 파트너로 함께 돌립니다." },
        { num: "02", ko: "브랜드 SNS 운영", en: "Brand SNS",
          body: "인스타그램·스레드 중심의 콘텐츠 제작과 계정 운영. 주간 캘린더와 월간 성과 리포트로 꾸준한 성장을 설계합니다." },
        { num: "03", ko: "리브랜딩", en: "Re-Branding",
          body: "브랜드 진단부터 아이덴티티 재정립, 채널별 톤앤매너 적용까지. 자체 개발한 '5단계 리브랜딩 캔버스'를 기반으로 운영합니다." },
        { num: "04", ko: "브랜드 컨설팅", en: "Brand Consulting",
          body: "시즌 기획, 상품 구성, 가격 전략, 채널 구성에 대한 자문. 창업 3~5년 차 브랜드의 다음 단계를 함께 정의합니다." },
      ],
      clients: ["AUBE SEOUL", "SUNNIESSTUDOS", "VIVICATE", "RUHEL", "DANCINGGRANDMA", "KYMA"],
      contact: {
        email: "hello@dentdelion.kr",
        phone: "+82 2 1234 5678",
        address: "서울시 성동구 서울숲2길 18-14, 3F",
        instagram: "@dentdelion",
      },
      about: [
        "덴트델리온은 패션 브랜드의 운영과 전략을 설계하는 에이전시입니다.",
        "브랜드의 시작부터 다음 시즌까지, 진단·전략·실행·리뷰의 사이클을 함께 돌립니다.",
        "한 시즌의 성공이 아닌, 3~5년 뒤에도 살아남는 브랜드를 만듭니다.",
      ],
    };